### ISSUE TITLE
Missing KiCad project file.

### ISSUE THREAD

**Issue by paulvdhoeven** [roscopeco/rosco_m68k#17]
I just cloned your project because I am curious what you made of it in the mean time.

Then I discovered that the KiCad project file is missing. Without it KiCad can not be opened in project mode and the link between schematic and PCB is broken. The most logical explanation is that you forgot to put this file in git.

I also saw you entered blue text strings into the title block:
![image](https://user-images.githubusercontent.com/48927628/77823451-978e2980-70fb-11ea-8e57-f11756204d36.png)

These texts should be added via:
**"Eeschema / File / Page Settings"**

**Comment by roscopeco** [comment]
Ah, many thanks (again!). I'd added `.pro` files to `.gitignore` for some reason, I've fixed now and the files are in `master`.

Also, noted your suggestion about the title block texts - I'll fix that soon.
